spring.application.name=ms_base
server.port=8081

# 1. URL DE CONEXIÓN
spring.datasource.url=jdbc:oracle:thin:@sanosysalvosdb_high?TNS_ADMIN=G:/Cloud/Wallet_sanosysalvosdb

# 2. CREDENCIALES
spring.datasource.username=admin
spring.datasource.password=DBsanosysalvos2026

# 3. HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# 4. FLYWAY
spring.flyway.enabled=true
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

spring.flyway.baseline-on-migrate=true
spring.flyway.baselineOnMigrate=true
spring.flyway.baseline-version=0